import localFont from "next/font/local";
import "./globals.css";
import CursorBall from "./Components/CursorBall";
import Header from "./Components/Uiux/Header";
import Footer from "./Components/Uiux/Footer";
const primaryfont = localFont({
  src: [
    {
      path: "../../public/fonts/Poppins-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${primaryfont.variable} antialiased`}
         cz-shortcut-listen="true"
      >
        <div className="max-w-[1980px] m-auto relative">
          <div className="absolute top-0 w-full z-50">
            <Header />
          </div>
          <CursorBall />
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
